name: Build Workflow

on: [push, pull_request]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
%jobsMarker%

  package:
    runs-on: ubuntu-latest
    needs: [%jobNeeds%]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

%downloadArtifacts%

      - name: Package All
        run: ./gradlew jnigenPackageAll
