name: Build Workflow

on: [push, pull_request]

jobs:
%jobsMarker%

  package:
    runs-on: ubuntu-latest
    needs: [%jobNeeds%]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

%downloadArtifacts%

      - name: Package All
        run: ./gradlew jnigenPackageAll
